version: '3.4'

services:
    plantuml-server:
        image: plantuml/plantuml-server
        restart: always
        networks:
            - "plantuml"


    plantuml-service:
        image: tizyjoshi/plantumlservice:latest
        depends_on:
            - plantuml-server
        restart: always
        ports:
            - "8080:80"
        networks:
            - "plantuml"

networks:
    plantuml: