version: '3.4'

services:
    plantuml-server:
        image: plantuml/plantuml-server
        restart: always
        networks:
            - "plantuml"


    plantuml-service:
        depends_on:
            - plantuml-server
        restart: always
        ports:
            - "8080:80"
        build:
            context: .
            dockerfile: plantuml-service/Dockerfile
        networks:
            - "plantuml"

networks:
    plantuml: